### PR TITLE
Support hiding of specific staff profiles

### PR DESCRIPTION
**Pull request by richaagarwal**
See platform issue 2532 and related PR https://github.com/cfpb/collab/pull/74 (which should get merged in first so the migration can be applied).

@Scotchester and I paired on this. 

Since we needed to update several places where queries were being made, we created a new function `_apply_profile_filters` to reduce redundancy and encapsulate the logic for how profiles are displayed on directory pages.  We use the new `hide_profile` field introduced in https://github.com/cfpb/collab/pull/74 in this function to make sure we hide any specified profiles across different directory pages, as well as preventing the individual profile from loading.  However this does not yet prevent the profile from appearing in search results if you search for that person.

### CODE REVIEW

File: staff_directory/views.py [hunk 1]
```diff
@@ -24,14 +24,15 @@
 from core.notifications.models import Notification
 from core.notifications.email import EmailInfo
 from core.taggit.models import Tag, TaggedItem
-from staff_directory.helpers import _get_emails_for_tag, \
-    _set_remove_tag_permission, _query_profile_tags, \
-    _set_taggers, _query_tags_for_people, STAFF_DIR_TAG_CATEGORIES
+from staff_directory.helpers import _apply_profile_filters, \
```
Comment (richaagarwal) [inline staff_directory/views.py]: Just some alphabetizing

**Comment by higs4281** [comment]
Just an idea, but couldn't you add a model manager to core.models.Person that always checks for the hidden value?

**Comment by richaagarwal** [comment]
@higs4281 That's a great idea, I hadn't thought of that. Let me try that and I'll place this on hold for now.

**Comment by richaagarwal** [comment]
@higs4281 I'm looking into this now, but it would still require changing over all queries to use the manager syntax `Person.people` instead of `Person.objects`. This becomes an issue with our use of Haystack for example, where we then get the error:
```
Exception Value: | type object 'Person' has no attribute 'objects'
/Users/agarwalr/apps/collab/venv/lib/python2.7/site-packages/haystack/backends/simple_backend.py in search, line 77
```
Do you know of an easy workaround for that? 

Otherwise, I think I'll probably opt for these changes to go in for now.

**Comment by higs4281** [comment]
You should be able to re-define the "objects" attribute in your manager. You don't have to call it "people."

**Comment by richaagarwal** [comment]
Okay, so adding that logic at the manager level then causes other side effects, like preventing a person from logging in, which we don't want to do...

**Comment by higs4281** [comment]
Didn't anticipate that. Sorry for the churn, @richaagarwal.

**Comment by richaagarwal** [comment]
@higs4281 No worries! It was worth looking into.  I'm not sure why it's grabbing a person's profile (as opposed to just user info) when logging in, so I'll briefly look into that.

**Comment by Scotchester** [comment]
Figured out how to run the migration and test this locally. Works great! :+1:
